# Data Cleaning

## Inspection

In [3]:
import pandas as pd
import numpy as np

In [4]:
sleep = pd.read_csv('sleep_doomscrolling_habits.csv')
sleep.head()

,respondent_id,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,...,occupation_status,country_region,primary_device_used_at_night,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category
0,D30000,22,13.0,1.85,2,5.4,8.1,19.0,2,155.0,...,Unemployed,Germany,Tablet,Meditation/Journaling,Yes,Yes,Yes,No,Yes,Good
1,D30001,18,90.0,3.61,3,29.6,7.0,31.0,3,82.0,...,Student,India,Smartphone,Meditation/Journaling,No,Yes,Yes,No,Yes,Poor
2,D30002,37,51.0,5.15,3,15.5,7.1,24.0,2,49.0,...,Student,India,Laptop,Reading,No,Yes,No,Yes,Yes,Fair
3,D30003,27,53.0,3.74,0,51.4,8.4,35.0,0,42.0,...,NaN,United States,Smartphone,No Fixed Routine,No,Yes,Yes,No,No,Fair
4,D30004,17,67.0,6.09,2,32.2,7.2,19.0,1,76.0,...,Employed Part-time,United States,Smartphone,Watching Videos,No,No,No,No,No,Fair

In [5]:
sleep.dtypes

respondent_id                         str
age                                 int64
bedtime_screen_time_minutes       float64
total_daily_screen_time_hours     float64
doomscroll_sessions_per_night       int64
avg_doomscroll_session_minutes    float64
sleep_hours_per_night             float64
sleep_latency_minutes             float64
number_of_night_wakeups             int64
caffeine_intake_mg_per_day        float64
anxiety_score                       int64
stress_score                        int64
sleep_quality_score               float64
daytime_fatigue_score               int64
number_of_news_apps_used            int64
phone_checks_per_night              int64
exercise_minutes_per_day          float64
days_since_last_digital_detox     float64
weekly_sleep_debt_hours           float64
gender                                str
occupation_status                     str
country_region                        str
primary_device_used_at_night          str
bedtime_routine_type                  str
uses_night_mode                       str
keeps_phone_in_bedroom                str
consumes_negative_news_content        str
uses_sleep_tracking_app               str
doomscroller                          str
sleep_quality_category                str
dtype: object

In [6]:
sleep['sleep_quality_score'].isna().sum()

np.int64(40)

sleep_quality_score target has nulls. Need to drop those observations. Other potential targets don't have nulls.

## Drop redundant/necessary columns

In [7]:
# cant keep nulls on a target
sleep = sleep.dropna(subset=['sleep_quality_score'])
sleep = sleep.drop(columns='respondent_id')
len(sleep)

960

In [8]:
sleep.head()

,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,anxiety_score,...,occupation_status,country_region,primary_device_used_at_night,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category
0,22,13.0,1.85,2,5.4,8.1,19.0,2,155.0,5,...,Unemployed,Germany,Tablet,Meditation/Journaling,Yes,Yes,Yes,No,Yes,Good
1,18,90.0,3.61,3,29.6,7.0,31.0,3,82.0,5,...,Student,India,Smartphone,Meditation/Journaling,No,Yes,Yes,No,Yes,Poor
2,37,51.0,5.15,3,15.5,7.1,24.0,2,49.0,2,...,Student,India,Laptop,Reading,No,Yes,No,Yes,Yes,Fair
3,27,53.0,3.74,0,51.4,8.4,35.0,0,42.0,6,...,NaN,United States,Smartphone,No Fixed Routine,No,Yes,Yes,No,No,Fair
4,17,67.0,6.09,2,32.2,7.2,19.0,1,76.0,5,...,Employed Part-time,United States,Smartphone,Watching Videos,No,No,No,No,No,Fair

## Map yes/no to 0 and 1

In [9]:
sleep['doomscroller'].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [10]:
# verified that these only contain yes/no
binary_cols = ['uses_night_mode', 'keeps_phone_in_bedroom', 'consumes_negative_news_content', 'uses_sleep_tracking_app', 'doomscroller']
binary_map = {'Yes': 1, 'No': 0}


sleep[binary_cols] = sleep[binary_cols].replace(binary_map)

## Wrangle categoricals

In [11]:
categorical_nulls = ['occupation_status', 'primary_device_used_at_night', 'bedtime_routine_type']

sleep[categorical_nulls] = sleep[categorical_nulls].fillna('Unknown')

sleep.head()

,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,anxiety_score,...,occupation_status,country_region,primary_device_used_at_night,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category
0,22,13.0,1.85,2,5.4,8.1,19.0,2,155.0,5,...,Unemployed,Germany,Tablet,Meditation/Journaling,1,1,1,0,1,Good
1,18,90.0,3.61,3,29.6,7.0,31.0,3,82.0,5,...,Student,India,Smartphone,Meditation/Journaling,0,1,1,0,1,Poor
2,37,51.0,5.15,3,15.5,7.1,24.0,2,49.0,2,...,Student,India,Laptop,Reading,0,1,0,1,1,Fair
3,27,53.0,3.74,0,51.4,8.4,35.0,0,42.0,6,...,Unknown,United States,Smartphone,No Fixed Routine,0,1,1,0,0,Fair
4,17,67.0,6.09,2,32.2,7.2,19.0,1,76.0,5,...,Employed Part-time,United States,Smartphone,Watching Videos,0,0,0,0,0,Fair

In [12]:
sleep['sleep_quality_category'] = sleep['sleep_quality_category'].astype('category')

sleep.dtypes

age                                  int64
bedtime_screen_time_minutes        float64
total_daily_screen_time_hours      float64
doomscroll_sessions_per_night        int64
avg_doomscroll_session_minutes     float64
sleep_hours_per_night              float64
sleep_latency_minutes              float64
number_of_night_wakeups              int64
caffeine_intake_mg_per_day         float64
anxiety_score                        int64
stress_score                         int64
sleep_quality_score                float64
daytime_fatigue_score                int64
number_of_news_apps_used             int64
phone_checks_per_night               int64
exercise_minutes_per_day           float64
days_since_last_digital_detox      float64
weekly_sleep_debt_hours            float64
gender                                 str
occupation_status                      str
country_region                         str
primary_device_used_at_night           str
bedtime_routine_type                   str
uses_night_mode                     object
keeps_phone_in_bedroom              object
consumes_negative_news_content      object
uses_sleep_tracking_app             object
doomscroller                        object
sleep_quality_category            category
dtype: object

## Wrangle numerics: MEAN IMPUTATION

In [13]:
numerics_to_update = ['caffeine_intake_mg_per_day', 'exercise_minutes_per_day']

sleep[numerics_to_update] = sleep[numerics_to_update].fillna(sleep[numerics_to_update].mean())

In [14]:
sleep.head()

,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,anxiety_score,...,occupation_status,country_region,primary_device_used_at_night,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category
0,22,13.0,1.85,2,5.4,8.1,19.0,2,155.0,5,...,Unemployed,Germany,Tablet,Meditation/Journaling,1,1,1,0,1,Good
1,18,90.0,3.61,3,29.6,7.0,31.0,3,82.0,5,...,Student,India,Smartphone,Meditation/Journaling,0,1,1,0,1,Poor
2,37,51.0,5.15,3,15.5,7.1,24.0,2,49.0,2,...,Student,India,Laptop,Reading,0,1,0,1,1,Fair
3,27,53.0,3.74,0,51.4,8.4,35.0,0,42.0,6,...,Unknown,United States,Smartphone,No Fixed Routine,0,1,1,0,0,Fair
4,17,67.0,6.09,2,32.2,7.2,19.0,1,76.0,5,...,Employed Part-time,United States,Smartphone,Watching Videos,0,0,0,0,0,Fair

In [15]:
sleep.isna().sum()

age                               0
bedtime_screen_time_minutes       0
total_daily_screen_time_hours     0
doomscroll_sessions_per_night     0
avg_doomscroll_session_minutes    0
sleep_hours_per_night             0
sleep_latency_minutes             0
number_of_night_wakeups           0
caffeine_intake_mg_per_day        0
anxiety_score                     0
stress_score                      0
sleep_quality_score               0
daytime_fatigue_score             0
number_of_news_apps_used          0
phone_checks_per_night            0
exercise_minutes_per_day          0
days_since_last_digital_detox     0
weekly_sleep_debt_hours           0
gender                            0
occupation_status                 0
country_region                    0
primary_device_used_at_night      0
bedtime_routine_type              0
uses_night_mode                   0
keeps_phone_in_bedroom            0
consumes_negative_news_content    0
uses_sleep_tracking_app           0
doomscroller                      0
sleep_quality_category            0
dtype: int64

In [17]:
sleep.head().T

,0,1,2,3,4
age,22,18,37,27,17
bedtime_screen_time_minutes,13.0,90.0,51.0,53.0,67.0
total_daily_screen_time_hours,1.85,3.61,5.15,3.74,6.09
doomscroll_sessions_per_night,2,3,3,0,2
avg_doomscroll_session_minutes,5.4,29.6,15.5,51.4,32.2
sleep_hours_per_night,8.1,7.0,7.1,8.4,7.2
sleep_latency_minutes,19.0,31.0,24.0,35.0,19.0
number_of_night_wakeups,2,3,2,0,1
caffeine_intake_mg_per_day,155.0,82.0,49.0,42.0,76.0
anxiety_score,5,5,2,6,5
stress_score,7,6,2,6,7
sleep_quality_score,5.0,3.0,5.0,5.0,5.0
daytime_fatigue_score,6,9,8,4,7
number_of_news_apps_used,3,2,0,1,3
phone_checks_per_night,3,3,3,0,3
exercise_minutes_per_day,103.0,28.0,11.0,61.0,23.0
days_since_last_digital_detox,9.0,24.0,15.0,13.0,19.0
weekly_sleep_debt_hours,0.7,7.5,2.9,0.0,5.4
gender,Male,Male,Prefer not to say,Prefer not to say,Prefer not to say
occupation_status,Unemployed,Student,Student,Unknown,Employed Part-time
country_region,Germany,India,India,United States,United States
primary_device_used_at_night,Tablet,Smartphone,Laptop,Smartphone,Smartphone
bedtime_routine_type,Meditation/Journaling,Meditation/Journaling,Reading,No Fixed Routine,Watching Videos
uses_night_mode,1,0,0,0,0
keeps_phone_in_bedroom,1,1,1,1,0
consumes_negative_news_content,1,1,0,1,0
uses_sleep_tracking_app,0,0,1,0,0
doomscroller,1,1,1,0,0
sleep_quality_category,Good,Poor,Fair,Fair,Fair

## Need to one hot encode specific to model. This is about as far as we can take things before building the model